---
abstract: 'Remote ubic admin'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Ubic
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 4.30
  Ubic: 1.50
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mojolicious-Plugin-Ubic
  homepage: https://metacpan.org/release/Mojolicious-Plugin-Ubic
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jhthorsen/mojolicious-plugin-ubic
version: 0.04
